export enum FinderTypeE {
  variableObject = "variableObject",
  variableArray = "variableArray",
  switch = "switch",
  tsEnum = "tsEnum",
  import = "import",
  export = "export",
  defaultExport = "defaultExport",
  program = "program",
  classBody = "classBody",
  jsxElement = "jsxElement",
  tsInterfaceBody = "tsInterfaceBody",
  tsTypeAlias = "tsTypeAlias",
  tsTypeLiteral = "tsTypeLiteral",
  tsNamespace = "tsNamespace",
  existingImport = "existingImport",
  useEffect = "useEffect",
  function = "function",
  return = "return"
}
